/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const BusinessIdea = IDL.Record({
  'creator' : IDL.Principal,
  'idea' : IDL.Text,
  'createdAt' : Time,
});
export const Post = IDL.Record({
  'upvotes' : IDL.Nat,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'createdAt' : Time,
  'author' : IDL.Principal,
  'category' : IDL.Text,
});
export const Goal = IDL.Record({
  'title' : IDL.Text,
  'owner' : IDL.Principal,
  'createdAt' : Time,
  'progress' : IDL.Nat,
});
export const Task = IDL.Record({
  'title' : IDL.Text,
  'owner' : IDL.Principal,
  'completed' : IDL.Bool,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBusinessIdea' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeTask' : IDL.Func([IDL.Text], [], []),
  'createGoal' : IDL.Func([IDL.Text], [], []),
  'createPost' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'createTask' : IDL.Func([IDL.Text], [], []),
  'getAllBusinessIdeas' : IDL.Func([], [IDL.Vec(BusinessIdea)], ['query']),
  'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getCallerGoals' : IDL.Func([], [IDL.Vec(Goal)], ['query']),
  'getCallerTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPostsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Post)], ['query']),
  'getRandomBusinessIdea' : IDL.Func([], [IDL.Opt(BusinessIdea)], []),
  'getTopPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateGoalProgress' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'upvotePost' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const BusinessIdea = IDL.Record({
    'creator' : IDL.Principal,
    'idea' : IDL.Text,
    'createdAt' : Time,
  });
  const Post = IDL.Record({
    'upvotes' : IDL.Nat,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'createdAt' : Time,
    'author' : IDL.Principal,
    'category' : IDL.Text,
  });
  const Goal = IDL.Record({
    'title' : IDL.Text,
    'owner' : IDL.Principal,
    'createdAt' : Time,
    'progress' : IDL.Nat,
  });
  const Task = IDL.Record({
    'title' : IDL.Text,
    'owner' : IDL.Principal,
    'completed' : IDL.Bool,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBusinessIdea' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeTask' : IDL.Func([IDL.Text], [], []),
    'createGoal' : IDL.Func([IDL.Text], [], []),
    'createPost' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'createTask' : IDL.Func([IDL.Text], [], []),
    'getAllBusinessIdeas' : IDL.Func([], [IDL.Vec(BusinessIdea)], ['query']),
    'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getCallerGoals' : IDL.Func([], [IDL.Vec(Goal)], ['query']),
    'getCallerTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPostsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Post)], ['query']),
    'getRandomBusinessIdea' : IDL.Func([], [IDL.Opt(BusinessIdea)], []),
    'getTopPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateGoalProgress' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'upvotePost' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };